"""β-2 Auxiliary Head Label Loading and Vectorization

Loads threat-awareness and type-effectiveness labels generated by β-1,
then attaches them to training examples for auxiliary-head supervision.
"""

from __future__ import annotations

import json
from typing import Any, Dict, List, Optional, Tuple

import numpy as np


def load_beta_labels(labels_jsonl_path: str) -> Dict[Tuple[str, int, str], Dict[str, Any]]:
    """Load β-1 generated labels keyed by (battle_id, turn_number, player).

    Args:
        labels_jsonl_path: Path to artifacts/beta_labels_v1/labels.jsonl

    Returns:
        Dict mapping (battle_id, turn_number, player) → {threat_score, action_type_eff}

    Raises:
        FileNotFoundError: If labels file doesn't exist
    """
    labels_by_key = {}
    try:
        with open(labels_jsonl_path) as f:
            for line_num, line in enumerate(f, start=1):
                if not line.strip():
                    continue
                try:
                    label = json.loads(line)
                    key = (label["battle_id"], label["turn_number"], label["player"])
                    labels_by_key[key] = {
                        "threat_score": float(label["threat_score"]),
                        "action_type_eff": label.get("action_type_eff"),  # None for switches
                    }
                except (json.JSONDecodeError, KeyError, ValueError) as e:
                    raise ValueError(f"Line {line_num}: {e}")
    except FileNotFoundError:
        raise FileNotFoundError(
            f"β-1 labels not found at {labels_jsonl_path}. "
            "Run: python3.12 word_prediction_model/scripts/generate_beta_labels.py"
        )
    return labels_by_key


def attach_auxiliary_labels_to_examples(
    examples: List[Dict[str, Any]],
    labels_by_key: Dict[Tuple[str, int, str], Dict[str, Any]],
) -> Tuple[int, int]:
    """Mutate examples in-place to add threat_score and action_type_eff fields.

    Args:
        examples: Training examples from ingest_battles_to_examples
        labels_by_key: Label dict from load_beta_labels

    Returns:
        (num_matched, num_missing) — examples with/without labels

    Side effects:
        - Adds "threat_score" and "action_type_eff" fields to each example
        - Examples without labels get threat_score=0.0, action_type_eff=None
    """
    num_matched = 0
    num_missing = 0

    for ex in examples:
        key = (ex["battle_id"], ex["turn_number"], ex["player"])
        if key in labels_by_key:
            label = labels_by_key[key]
            ex["threat_score"] = label["threat_score"]
            ex["action_type_eff"] = label["action_type_eff"]
            num_matched += 1
        else:
            # Default values for examples not in β-1 corpus
            ex["threat_score"] = 0.0
            ex["action_type_eff"] = None
            num_missing += 1

    return num_matched, num_missing


def vectorize_auxiliary_labels(
    examples: List[Dict[str, Any]],
    policy_vocab_size: int,
) -> Tuple[np.ndarray, np.ndarray]:
    """Convert threat and type-eff labels to training targets.

    Args:
        examples: Training examples with threat_score and action_type_eff fields
        policy_vocab_size: Number of action classes (e.g., 357)

    Returns:
        (threat_targets, type_eff_targets) where:
        - threat_targets: (batch_size,) float32, raw threat scores
        - type_eff_targets: (batch_size, num_action_classes) float32
          For legal moves: type-eff multiplier
          For switches: NaN (masked in loss)
          For illegal moves: NaN (masked in loss)

    Note:
        This function does NOT know about legal moves. The caller must mask
        non-legal actions in the loss function or use sample_weight.
    """
    batch_size = len(examples)
    threat_targets = np.zeros(batch_size, dtype="float32")
    type_eff_targets = np.full((batch_size, policy_vocab_size), np.nan, dtype="float32")

    for i, ex in enumerate(examples):
        # Threat target: always present
        threat_targets[i] = ex.get("threat_score", 0.0)

        # Type-eff target: only for move actions
        action_type_eff = ex.get("action_type_eff")
        if action_type_eff is not None and not np.isnan(float(action_type_eff)):
            # For moves, set type-eff to the scalar multiplier across all actions
            # The model will learn which actions are legal via the policy head
            type_eff_targets[i, :] = float(action_type_eff)
            # This is a simplification: in production, you'd want per-move type-eff
            # For now, we're using a scalar that applies uniformly

    return threat_targets, type_eff_targets


def validate_label_coverage(examples: List[Dict[str, Any]]) -> Dict[str, Any]:
    """Check how many examples have threat/type-eff labels.

    Returns:
        {"total": int, "with_threat": int, "with_type_eff": int, "coverage_pct": float}
    """
    total = len(examples)
    with_threat = sum(1 for ex in examples if ex.get("threat_score") is not None)
    with_type_eff = sum(
        1 for ex in examples if ex.get("action_type_eff") is not None
    )

    return {
        "total": total,
        "with_threat": with_threat,
        "with_type_eff": with_type_eff,
        "coverage_pct_threat": 100.0 * with_threat / total if total > 0 else 0.0,
        "coverage_pct_type_eff": 100.0 * with_type_eff / total if total > 0 else 0.0,
    }
